version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: monthly
      day: wednesday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: monthly
      day: wednesday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)
